DEFAULT_LEFT_PANEL_WIDTH = 390
DEFAULT_CENTER_PANEL_WIDTH = 780
DEFAULT_RIGHT_PANEL_WIDTH = 430

DEFAULT_THREE_PANEL_SPLITTER_SIZES = [
    DEFAULT_LEFT_PANEL_WIDTH,
    DEFAULT_CENTER_PANEL_WIDTH,
    DEFAULT_RIGHT_PANEL_WIDTH,
]
